[package]
name = "native_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
core_types = { version = "0.1.0", path = "../core_types" }
device_query = "4.0.1"
rfd = "0.17.2"
tray-icon = "0.21.3"
winit = "0.30.13"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.4"
objc2 = "0.5.2"
objc2-app-kit = { version = "0.2.2", features = ["NSScreen", "NSView", "NSWindow"] }
objc2-foundation = "0.2.2"
readmouse = "0.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52.0", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi", "Win32_UI_Controls", "Win32_UI_WindowsAndMessaging"] }
